name: Publish NuGet packages
description: Publish NuGet packages

inputs:
  nuget-folder:
    description: Output folder for the NuGet package
    required: false
    default: ${{ github.workspace }}/artifacts/nuget
  registry-token:
    description: Registry token
    required: true
    default: ""
  package-version:
    description: Package version
    required: true
    default: ""
  registry:
    description: nuget.org or github
    required: true
    default: ""

runs:
  using: "composite"

  steps:
    - name: Create package
      run: |
        dotnet pack \
          --configuration Release \
          --no-build \
          --output ${{ inputs.nuget-folder }} \
          --include-symbols \
          -p:SymbolPackageFormat=snupkg \
          -p:PackageVersion=${{ inputs.package-version }} \
          -p:PublishRepositoryUrl=true
      shell: bash

    - name: Push CrossValidation package
      run: |
        dotnet nuget push ${{ format('{0}/*.nupkg', inputs.nuget-folder) }} \
          --source ${{ inputs.registry }} \
          --api-key ${{ inputs.registry-token }}
      shell: bash
