name: Publish NuGet
description: Publish NuGet

inputs:
  nuget-folder:
    description: Output folder for the NuGet package
    required: false
    default: ${{ github.workspace }}/generated/nuget
  nuget-api-key:
    description: Output folder for the NuGet package
    required: true
    default: ""
  package-version:
    description: Package version
    required: true
    default: ""
  project:
    description: Project
    required: true
    default: ""
  project-name:
    description: Project name
    required: true
    default: ""

runs:
  using: "composite"

  steps:
    - name: Create package
      run: |
        dotnet pack ${{ inputs.project }} \
          --configuration Release \
          --no-build \
          --output ${{ inputs.nuget-folder }} \
          --include-symbols \
          -p:SymbolPackageFormat=snupkg \
          -p:PackageVersion=${{ inputs.package-version }} \
          -p:PublishRepositoryUrl=true
      shell: bash

    - name: Push package
      run: |
        dotnet nuget push ${{ format('{0}/{1}.{2}.snupkg', inputs.nuget-folder, inputs.project-name, inputs.package-version) }} \
          --source https://api.nuget.org/v3/index.json \
          --api-key ${{ inputs.nuget-api-key }}
      shell: bash
