//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossValidation.ErrorResources {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CrossValidation.ErrorResources.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string InclusiveLengthRange {
            get {
                return ResourceManager.GetString("InclusiveLengthRange", resourceCulture);
            }
        }
        
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        public static string NotNull {
            get {
                return ResourceManager.GetString("NotNull", resourceCulture);
            }
        }
        
        public static string Enum {
            get {
                return ResourceManager.GetString("Enum", resourceCulture);
            }
        }
        
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        public static string MinimumLength {
            get {
                return ResourceManager.GetString("MinimumLength", resourceCulture);
            }
        }
        
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        public static string Generic {
            get {
                return ResourceManager.GetString("Generic", resourceCulture);
            }
        }
        
        public static string NotEmptyString {
            get {
                return ResourceManager.GetString("NotEmptyString", resourceCulture);
            }
        }
        
        public static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        public static string EmptyCollection {
            get {
                return ResourceManager.GetString("EmptyCollection", resourceCulture);
            }
        }
        
        public static string NotEmptyCollection {
            get {
                return ResourceManager.GetString("NotEmptyCollection", resourceCulture);
            }
        }
        
        public static string MaximumLength {
            get {
                return ResourceManager.GetString("MaximumLength", resourceCulture);
            }
        }
        
        public static string GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("GreaterThanOrEqual", resourceCulture);
            }
        }
        
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        public static string LessThanOrEqual {
            get {
                return ResourceManager.GetString("LessThanOrEqual", resourceCulture);
            }
        }
        
        public static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        public static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }
        
        public static string ExclusiveLengthRange {
            get {
                return ResourceManager.GetString("ExclusiveLengthRange", resourceCulture);
            }
        }
        
        public static string MinimumItems {
            get {
                return ResourceManager.GetString("MinimumItems", resourceCulture);
            }
        }
        
        public static string MaximumItems {
            get {
                return ResourceManager.GetString("MaximumItems", resourceCulture);
            }
        }
        
        public static string InclusiveRange {
            get {
                return ResourceManager.GetString("InclusiveRange", resourceCulture);
            }
        }
        
        public static string ExclusiveRange {
            get {
                return ResourceManager.GetString("ExclusiveRange", resourceCulture);
            }
        }
        
        public static string UniqueItems {
            get {
                return ResourceManager.GetString("UniqueItems", resourceCulture);
            }
        }
    }
}
