name: Publish coverage
description: Publish coverage

inputs:
  test-coverage-folder:
    description: Folder where the coverage files are located
    required: false
    default: ${{ github.workspace }}/generated/coverage

  github-token:
    description: GitHub token
    required: true
    default: ""

runs:
  using: "composite"

  steps:
    # - name: Copy coverage to a predictable location
    #   run: cp ${{ inputs.test-coverage-folder }}/*/coverage.info ${{ inputs.test-coverage-folder }}/lcov.info
    #   shell: bash

    # - name: Publish coverage to Coveralls
    #   uses: coverallsapp/github-action@v2.1.2
    #   with:
    #     github-token: ${{ inputs.github-token }}
    #     file: ${{ inputs.test-coverage-folder }}/lcov.info

    - name: Refresh coverage badge in README.md
      run: |
        current_milliseconds=$(date '+%s')
        new_value="\&coveralls_badge_current_milliseconds=$current_milliseconds)"
        awk -v new_value="$new_value" '{sub(/\&coveralls_badge_current_milliseconds=[^)]*\)/, new_value)}1' README.md > README_new.md
        mv README_new.md README.md
      shell: bash

    # - name: Save original branch name
    #   id: save-original-branch-name
    #   run: echo "ORIGINAL_BRANCH_NAME=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
    #   shell: bash

    - name: Commit README changes
      with:
        ref: ${{ github.ref_name }}
      run: |
        git config --local user.email "github-action@users.noreply.github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Refresh coverage badge in README.md"
        git push origin HEAD:$GITHUB_HEAD_REF
      shell: bash
