name: Publish coverage
description: Publish coverage

inputs:
  test-coverage-folder:
    description: Folder where the coverage files are located
    required: false
    default: ${{ github.workspace }}/artifacts/coverage

  github-token:
    description: GitHub token
    required: true
    default: ""

runs:
  using: "composite"

  steps:
    - name: Copy coverage to a predictable location
      run: cp ${{ inputs.test-coverage-folder }}/*/lcov.info ${{ inputs.test-coverage-folder }}/lcov.info
      shell: bash

    - name: Publish coverage to Coveralls
      uses: coverallsapp/github-action@v2.1.2
      with:
        github-token: ${{ inputs.github-token }}
        file: ${{ inputs.test-coverage-folder }}/lcov.info

    - name: Refresh coverage badge in README.md
      run: |
        current_milliseconds=$(date '+%s')
        new_value="coveralls_badge_current_milliseconds=$current_milliseconds)"
        awk -v new_value="$new_value" '{sub(/coveralls_badge_current_milliseconds=[^)]*\)/, new_value)}1' README.md > README_new.md
        mv README_new.md README.md
      shell: bash

    - name: Refresh coverage badge in README.md
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: Refresh coverage badge in README.md
        file_pattern: "README.md"
