name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TEST_COVERAGE_FOLDER: ${{ github.workspace }}/generated/coverage
  TEST_COVERAGE_REPORT_FOLDER: ${{ github.workspace }}/generated/coverage_report

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test \
            --configuration Release \
            --no-build \
            --verbosity normal \
            --collect:"XPlat Code Coverage" \
            --results-directory ${{ env.TEST_COVERAGE_FOLDER }}

      - name: Copy coverage to a predictable location
        run: cp ${{ env.TEST_COVERAGE_FOLDER }}/*/coverage.cobertura.xml ${{ env.TEST_COVERAGE_FOLDER }}/coverage.cobertura.xml

      - name: Generate test coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.17
        with:
          reports: ${{ env.TEST_COVERAGE_FOLDER }}/coverage.cobertura.xml
          targetdir: ${{ env.TEST_COVERAGE_REPORT_FOLDER }}
          reporttypes: HTML;MarkdownSummaryGithub

      - name: Add pull request comment with the code coverage summary
        uses: marocchino/sticky-pull-request-comment@v2.5.0
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: ${{ env.TEST_COVERAGE_REPORT_FOLDER }}/SummaryGithub.md

      - name: Add code coverage summary to the job summary
        run: cat ${{ env.TEST_COVERAGE_REPORT_FOLDER }}/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: TestCoverageReport
          path: ${{ env.TEST_COVERAGE_REPORT_FOLDER }}
