name: Main

on:
  push:
    branches:
      - main

jobs:
  execute:
    name: Execute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build

      - name: Test
        uses: ./.github/actions/test-with-coverage

      - name: Set package version
        id: set-package-version
        run: echo "PACKAGE_VERSION=$(date '+%Y.%-m.%s')-commit.$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Publish all packages to github
        uses: ./.github/actions/publish-all-packages
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          registry: github
          package-version: ${{ steps.set-package-version.outputs.PACKAGE_VERSION }}

      - name: Delete all the oldest packages
        uses: ./.github/actions/delete-all-oldest-packages
