name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  execute:
    name: Execute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build

      - name: Test
        uses: ./.github/actions/test-with-coverage

      - name: Publish coverage
        uses: ./.github/actions/publish-coverage
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
