name: Push to main

on:
  push:
    branches:
      - main

env:
  TEST_COVERAGE_FOLDER: ${{ github.workspace }}/generated/coverage

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/workflows/common/build.yml@main

      # https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#passing-runsettings-arguments-through-commandline
      - name: Test
        run: |
          dotnet test \
            --configuration Release \
            --no-build \
            --verbosity normal \
            --collect:"XPlat Code Coverage;Format=lcov" \
            --results-directory ./generated/coverage \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude="[*]CrossValidation.WebApplication*,[*]CrossValidation.Resources*"

      - name: Copy coverage to a predictable location
        run: cp ${{ env.TEST_COVERAGE_FOLDER }}/*/coverage.info ${{ env.TEST_COVERAGE_FOLDER }}/lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ env.TEST_COVERAGE_FOLDER }}/lcov.info

      - name: Refresh coverage badge
        run: curl -X PURGE https://camo.githubusercontent.com/c4fea259f903ccde969de79288d9a4bdc04d9eb5b6674d62c963490d13276a5b/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f416e64726575436f64696e612f43726f737356616c69646174696f6e2f62616467652e7376673f6272616e63683d6d61696e
