name: Push to main

on:
  push:
    branches:
      - feature/test-github-packages

jobs:
  execute:
    name: Execute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build

      # - name: Test
      #   uses: ./.github/actions/test-with-coverage

      # - name: Publish coverage
      #   uses: ./.github/actions/publish-coverage
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Refresh coverage badge
      #   run: curl -X PURGE https://camo.githubusercontent.com/c4fea259f903ccde969de79288d9a4bdc04d9eb5b6674d62c963490d13276a5b/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f416e64726575436f64696e612f43726f737356616c69646174696f6e2f62616467652e7376673f6272616e63683d6d61696e

      - name: Publish all packages to github
        uses: ./.github/actions/publish-all-packages
        with:
          repository-token: ${{ secrets.GITHUB_TOKEN }}
          repository: github
          package-version: 0.0.1-preview.1
