name: Release

on:
  release:
    types:
      - published

jobs:
  execute:
    name: Execute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build
        uses: ./.github/actions/build

      - name: Publish all packages to nuget.org
        uses: ./.github/actions/publish-all-packages
        with:
          repository-token: ${{ secrets.NUGET_API_KEY }}
          repository: nuget.org
          package-version: ${{ env.RELEASE_VERSION }}

      # It's not possible disable the artifact creation
      - name: Execute benchmarks
        run: |
          dotnet run \
            --project ./benchmarks/CrossValidation.Benchmarks/CrossValidation.Benchmarks.csproj \
            --configuration Release \
            -- --artifacts generated/benchmarks
