name: Release

on:
  release:
    types:
      - published

jobs:
  execute:
    name: Execute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build

      - name: Set release version
        id: set-release-version
        run: echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

      - name: Publish all packages to nuget.org
        uses: ./.github/actions/publish-all-packages
        with:
          registry-token: notValid
          registry: nuget.org
          package-version: ${{ steps.set-release-version.outputs.RELEASE_VERSION }}

      # https://aakinshin.net/posts/github-actions-perf-stability/
      # It's not possible disable the artifact creation
      - name: Execute benchmarks
        run: |
          dotnet run \
            --project ./benchmarks/CrossValidation.Benchmarks/CrossValidation.Benchmarks.csproj \
            --configuration Release \
            -- --artifacts generated/benchmarks
