name: Release

on:
  push
  # release:
  #   types:
  #     - published

jobs:
  execute:
    name: Execute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Print context
      #   run: echo "$GITHUB_CONTEXT"

      # - name: Print context2
      #   env:
      #     CONTEXT: ${{ toJson(github) }}
      #   run: echo "$CONTEXT"

      # - name: Build
      #   uses: ./.github/actions/build

      # - name: Debug Git information
      #   run: |
      #     git fetch --tags
      #     git tag -l
      #     git log --oneline --decorate --graph --all

      - name: Set release version
        id: set-release-version
        # run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # - name: Print release version
      #   env:
      #     MATRIX_CONTEXT: ${{ steps.set-release-version.outputs.RELEASE_VERSION }}
      #   run: echo "$MATRIX_CONTEXT"

      - name: Publish all packages to nuget.org
        uses: ./.github/actions/publish-all-packages
        with:
          registry-token: notValid
          registry: nuget.org
          package-version: ${{ env.RELEASE_VERSION }}

      # # https://aakinshin.net/posts/github-actions-perf-stability/
      # # It's not possible disable the artifact creation
      # - name: Execute benchmarks
      #   run: |
      #     dotnet run \
      #       --project ./benchmarks/CrossValidation.Benchmarks/CrossValidation.Benchmarks.csproj \
      #       --configuration Release \
      #       -- --artifacts generated/benchmarks
