name: Release

on:
  release:
    types:
      - published

jobs:
  execute:
    name: Execute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build
        uses: ./.github/actions/build

      - name: Publish NuGet
        uses: ./.github/actions/publish-nuget
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          package-version: ${{ env.RELEASE_VERSION }}
          project: src/CrossValidation/CrossValidation.csproj
          project-name: CrossValidation

      - name: Publish NuGet
        uses: ./.github/actions/publish-nuget
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          package-version: ${{ env.RELEASE_VERSION }}
          project: src/CrossValidation.ShouldlyAssertions/CrossValidation.ShouldlyAssertions.csproj
          project-name: CrossValidation.ShouldlyAssertions

      # It's not possible disable the artifact creation
      - name: Execute benchmarks
        run: |
          dotnet run \
            --project ./benchmarks/CrossValidation.Benchmarks/CrossValidation.Benchmarks.csproj \
            --configuration Release \
            -- --artifacts generated/benchmarks
